.TH SCALC 1 scalc\-VERSION
.SH NAME
.PP
scalc \- Simple calculator
.SH SYNOPSIS
.PP
.B scalc
.RB [ file ]
.SH DESCRIPTION
.PP
.B scalc 
is a very simple stack-based calculator that aims to be 
small, flexible, and extensible.
.PP
.B scalc 
reads RPN expressions from an interactive prompt, from a pipe, or from
.I file.
Results are provided in single-precision floats to stdout. 
When 
.B scalc 
is not run interactively, 
only the results are printed to stdout, 
not echoing any of the operations provided in the file itself.
.PP
Currently supported mathematical functions include 
basic arithmetic operations, square roots, and natural logarithms. 
All functions are defined in the
.I op.c
module in the source tree.
.PP
.B scalc 
accepts some commands, 
listed here for convenience, 
which modify scalc's behavior during a session:
.TP
.B :d
Drops the last element in stack.
.TP
.B :D
Drops all elements in the stack.
.TP
.B :p
Shows the last element in the stack.
.TP
.B :q
Quits 
.B scalc.
.SS Extending scalc math functions
.PP
.B scalc 
can be easily extended with new mathematical functions by adding them to the 
.I op.c
source file. 
The source file itself includes detailed instructions on how to do so.
.SH EXAMPLES
.PP
The following example showcases basic operation with 
.B scalc.
.PP
Default interactive mode:
.PP
.nf
.RS
.B "$ scalc"
.br 
.B "> 2 3 + 9 / 15 /"
.br
0.037037
.br
.B "> 90 *"
.br
3.333334
.br
.B "> ln"
.br
1.203973
.br
.B "> :q"
.RE
.fi
.PP
Reading from file:
.PP
.nf
.RS
.B "$ cat scalc_ex"
.br
67 9 -
.br
sqrt
.br
.B "$ scalc scalc_ex"
.br
7.615773
.RE
.fi
.PP
Reading from a pipeline:
.PP
.nf
.RS
.B "$ echo '34 ln' | scalc"
.br
3.526361
.RE
.fi
.SH SEE ALSO
.BR bc (1), dc (1) 